name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decrypt keystore
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in buildKey.jks.enc -out buildKey.jks -d || (echo "Decrypt key failed, use default key" && rm buildKey.jks)

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: Build debug APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildDebug
        with:
          arguments: assembleDebug
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build release APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildRelease
        with:
          arguments: assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildDebug.outcome == 'success' }}
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildRelease.outcome == 'success' }}
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
